version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.sqlFile
    ports:
      - "3306:3306"
